package hashtable;

import java.util.HashMap;
import java.util.Map;

/***
 * Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.

 Example:

 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e

 Explanation:
 'e' is the letter that was added.
 */

// 用两个map来记录出现次数，遇到第一个map里没有的或者发现出现次数超过第一个的就直接return
public class FindTheDifference389 {
    public char findTheDifference(String s, String t) {
        Map<Character, Integer> smap = new HashMap<>();
        Map<Character, Integer> tmap = new HashMap<>();

        for (char ch : s.toCharArray()) {
            smap.put(ch, smap.getOrDefault(ch, 0) + 1);
        }

        for (char ch : t.toCharArray()) {
            if(!smap.containsKey(ch)) {
                return ch;
            }
            else {
                tmap.put(ch, tmap.getOrDefault(ch, 0) + 1);
                if(smap.get(ch) < tmap.get(ch)) {
                    return ch;
                }
            }
        }
        return ' ';
    }
}
